// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzAPI.Contexts;

#nullable disable

namespace PizzAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323222631_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PizzAPI.Dtos.BebidaDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Ingredientes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Menu")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bebidas");

                    b.HasData(
                        new
                        {
                            Id = 41,
                            Descripcion = "Experimenta todo el sabor cola, refrescando y amplificando cada momento (113 Cal)",
                            Menu = 0,
                            Nombre = "Pepsi 600 ml",
                            Precio = 25m,
                            Ruta = "images/bebidas/5090ae51-956d-42b0-a51a-cf5af5636032.jpg"
                        },
                        new
                        {
                            Id = 42,
                            Descripcion = "Experimenta todo el sabor cola, refrescando y amplificando cada momento (113 Cal)",
                            Menu = 0,
                            Nombre = "Pepsi 1.5 litros",
                            Precio = 54m,
                            Ruta = "images/bebidas/5090ae51-956d-42b0-a51a-cf5af5636032.jpg"
                        },
                        new
                        {
                            Id = 43,
                            Descripcion = "Experimenta y comparte el gran sabor cola, sin calorias (0 Cal)",
                            Menu = 0,
                            Nombre = "Pepsi Ligth 600 ml",
                            Precio = 25m,
                            Ruta = "images/bebidas/48dc6f3f-c5be-45fa-892e-c7064994f642.jpg"
                        },
                        new
                        {
                            Id = 44,
                            Descripcion = "Experimenta y comparte el gran sabor cola, sin calorias (0 Cal)",
                            Menu = 0,
                            Nombre = "Pepsi Ligth 1.5 litros",
                            Precio = 54m,
                            Ruta = "images/bebidas/48dc6f3f-c5be-45fa-892e-c7064994f642.jpg"
                        },
                        new
                        {
                            Id = 45,
                            Descripcion = "Agua, burbujas y los refrescantes sabores naturales de la lima & limón (0 Cal)",
                            Menu = 0,
                            Nombre = "7up 600 ml",
                            Precio = 32m,
                            Ruta = "images/bebidas/0760521a-dcb5-4be7-b481-fa8b22ed8b88.jpg"
                        },
                        new
                        {
                            Id = 46,
                            Descripcion = "Agua, burbujas y los refrescantes sabores naturales de la lima & limón (0 Cal).",
                            Menu = 0,
                            Nombre = "7up 1.5 litros",
                            Precio = 54m,
                            Ruta = "images/bebidas/0760521a-dcb5-4be7-b481-fa8b22ed8b88.jpg"
                        },
                        new
                        {
                            Id = 47,
                            Descripcion = "Agua purificada que te hidrata y cuida tu corazón por no contener sodio (0 Cal)",
                            Menu = 0,
                            Nombre = "E-Pura Natural 600 ml",
                            Precio = 32m,
                            Ruta = "images/bebidas/95f1a30b-62f8-4e4a-8f11-644e8a047e79.jpg"
                        });
                });

            modelBuilder.Entity("PizzAPI.Dtos.MasaDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Masas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "La original y clásica masa fresca hecha al momento con orilla dorada y espolvoreada de especias que le dan nuestro toque único.",
                            Nombre = "Original"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Masa fresca hecha al momento con deliciosa orilla dorada rellena de queso mozzarella derretido y espolvoreada con especias.",
                            Nombre = "Orilla rellena de queso"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Masa dorada y esponjosa con toque de mantequilla, doble capa de queso (provolone y mozzarella) e ingredientes hasta la orilla.",
                            Nombre = "Sartén"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Masa delgada y crujiente con borde dorado, perfecta para resaltar el sabor de los ingredientes y ofrecer una experiencia más ligera.",
                            Nombre = "Crunchy"
                        });
                });

            modelBuilder.Entity("PizzAPI.Dtos.ProductoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("Ingredientes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Carbonara",
                            Precio = 0m,
                            Ruta = "/images/pizzas/022238e3-ac62-45af-b765-379a077a9b26.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Triple peperoni",
                            Precio = 0m,
                            Ruta = "/images/pizzas/00455854-40f9-45e2-a241-b03e70dfe6cc.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Peperoni",
                            Precio = 0m,
                            Ruta = "/images/pizzas/be242cad-08db-4b00-becd-be48a9fb86a4.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Hawaiina",
                            Precio = 0m,
                            Ruta = "/images/pizzas/75b89c2b-2c59-4225-8478-4e9ab4432ec9.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Mexicana",
                            Precio = 0m,
                            Ruta = "/images/pizzas/7f339d0c-bf13-4839-a9dc-de6721210a5b.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Ingredientes = "[\"Salsa BBQ\",\"Salsa de tomate\",\"Carne molida\",\"Pollo\",\"Tocino\"]",
                            Nombre = "Texas bbq",
                            Precio = 0m,
                            Ruta = "/images/pizzas/67734d82-5c38-40f8-a311-255c0d157bd5.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Cuatro quesos",
                            Precio = 0m,
                            Ruta = "images/pizzas/0ad30a1e-d7ed-4384-9b1e-b8a5c9587174.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Pepperoni especial",
                            Precio = 0m,
                            Ruta = "images/pizzas/8be27c50-bb3c-4774-ac8f-a41f42029617.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Carnes frias",
                            Precio = 0m,
                            Ruta = "images/pizzas/f8748c06-e178-4d38-b99c-a522ad450a86.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Chicken hawaiina",
                            Precio = 0m,
                            Ruta = "images/pizzas/49249843-d9af-4356-bcac-ae94e3357742.jpg"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Honolulu",
                            Precio = 0m,
                            Ruta = "images/pizzas/cdcef20a-407a-488e-9751-6f481a871048.jpg"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Veggie",
                            Precio = 0m,
                            Ruta = "images/pizzas/3f362b55-3f56-47f9-b67a-ff49eb10f66a.jpg"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Extravaganzza",
                            Precio = 0m,
                            Ruta = "images/pizzas/db99ef86-f2b8-4a8e-8afb-5ad4409e4233.jpg"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Deluxe",
                            Precio = 0m,
                            Ruta = "images/pizzas/9614b6f3-0def-4ace-8c5d-e0954d899a5b.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
